apiVersion: shipper.booking.com/v1
kind: Application
metadata:
  name: jarruda
  labels:
    service-directory.project: jarruda
    service-directory.service: playground
    dev_cleanup_disable: 'true'
spec:
  revisionHistoryLimit: 1
  template:
    clusterRequirements:
      regions:
        - name: eu-nl
      capabilities: []
    chart:
      name: nodejs
      version: ^3
      repoUrl: https://artifactory.booking.com/charts
    values:
      name: jarruda
      stagingService:
        enabled: false
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
      image: PERSONAL_DEV_REPO:latest
      ports:
        80: '3000'
        443: '3000'
        8080: '8080'
      sidecars:
        envoy:
          enabled: true
          resources:
            limits:
              cpu: 1000m
              memory: 768Mi
            requests:
              cpu: 1000m
              memory: 400Mi
    strategy:
      steps:
        - name: full on
          capacity:
            incumbent: 0
            contender: 100
          traffic:
            incumbent: 0
            contender: 100
